<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-CoreWatch.Atlas.Agent-12260ca6-a0f6-4b63-bccc-1bd762b3091c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreWatch.Atlas.Contracts\CoreWatch.Atlas.Contracts.csproj" />
    <ProjectReference Include="..\CoreWatch.Atlas.Collectors.Linux\CoreWatch.Atlas.Collectors.Linux.csproj" />
    <ProjectReference Include="..\CoreWatch.Atlas.Collectors.Windows\CoreWatch.Atlas.Collectors.Windows.csproj" />
  </ItemGroup>
</Project>
