using System.Security.Cryptography;
using Microsoft.AspNetCore.WebUtilities;

namespace CoreWatch.Atlas.Server;

public sealed record ApiTokenSummary(long Id,string Name,string Scope,DateTimeOffset? ExpiresAtUtc,DateTimeOffset? RevokedAtUtc,string CreatedBy,DateTimeOffset CreatedAtUtc);
public sealed record ApiTokenRequest(string Name,string Scope,DateTimeOffset? ExpiresAtUtc);
public sealed record IssuedApiToken(ApiTokenSummary Token,string Value);
public sealed record ApiAuditRecord(long Id,long? TokenId,string Method,string Path,int StatusCode,string? RemoteAddress,DateTimeOffset OccurredAtUtc);

public sealed partial class AtlasDatabase
{
    public async Task<IssuedApiToken> CreateApiTokenAsync(ApiTokenRequest x,string user,CancellationToken ct=default)
    { if(string.IsNullOrWhiteSpace(x.Name)||x.Name.Length>80||!new[]{"read","alerts","admin"}.Contains(x.Scope)||x.ExpiresAtUtc<=_timeProvider.GetUtcNow())throw new ArgumentException("Invalid API token.");var value="catlas_api_"+WebEncoders.Base64UrlEncode(RandomNumberGenerator.GetBytes(32));var now=_timeProvider.GetUtcNow();await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="INSERT INTO api_tokens(name,token_hash,scope,expires_at_utc,created_by,created_at_utc) VALUES($name,$hash,$scope,$expires,$user,$now);SELECT last_insert_rowid();";q.Parameters.AddWithValue("$name",x.Name.Trim());q.Parameters.Add("$hash",Microsoft.Data.Sqlite.SqliteType.Blob).Value=HashToken(value);q.Parameters.AddWithValue("$scope",x.Scope);q.Parameters.AddWithValue("$expires",x.ExpiresAtUtc is null?DBNull.Value:FormatTimestamp(x.ExpiresAtUtc.Value));q.Parameters.AddWithValue("$user",user);q.Parameters.AddWithValue("$now",FormatTimestamp(now));var id=Convert.ToInt64(await q.ExecuteScalarAsync(ct));return new(new(id,x.Name.Trim(),x.Scope,x.ExpiresAtUtc,null,user,now),value); }
    public async Task<IReadOnlyList<ApiTokenSummary>> ListApiTokensAsync(CancellationToken ct=default)
    { await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT id,name,scope,expires_at_utc,revoked_at_utc,created_by,created_at_utc FROM api_tokens ORDER BY id DESC;";await using var r=await q.ExecuteReaderAsync(ct);var result=new List<ApiTokenSummary>();while(await r.ReadAsync(ct))result.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.IsDBNull(3)?null:ParseTimestamp(r.GetString(3)),r.IsDBNull(4)?null:ParseTimestamp(r.GetString(4)),r.GetString(5),ParseTimestamp(r.GetString(6))));return result; }
    public async Task<bool> RevokeApiTokenAsync(long id,CancellationToken ct=default){await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="UPDATE api_tokens SET revoked_at_utc=$now WHERE id=$id AND revoked_at_utc IS NULL;";q.Parameters.AddWithValue("$now",FormatTimestamp(_timeProvider.GetUtcNow()));q.Parameters.AddWithValue("$id",id);return await q.ExecuteNonQueryAsync(ct)==1;}
    public async Task<long?> AuthenticateApiTokenAsync(string? value,string requiredScope,string method,string path,string? remote,CancellationToken ct=default)
    { long? id=null;if(!string.IsNullOrWhiteSpace(value)&&value.Length<=128){await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT id FROM api_tokens WHERE token_hash=$hash AND revoked_at_utc IS NULL AND (expires_at_utc IS NULL OR expires_at_utc>$now) AND (scope=$scope OR scope='admin' OR ($scope='read' AND scope='alerts'));";q.Parameters.Add("$hash",Microsoft.Data.Sqlite.SqliteType.Blob).Value=HashToken(value);q.Parameters.AddWithValue("$now",FormatTimestamp(_timeProvider.GetUtcNow()));q.Parameters.AddWithValue("$scope",requiredScope);var found=await q.ExecuteScalarAsync(ct);if(found is not null)id=Convert.ToInt64(found);}await using(var c=await OpenConnectionAsync(ct)){await using var q=c.CreateCommand();q.CommandText="INSERT INTO api_audit(token_id,method,path,status_code,remote_address,occurred_at_utc) VALUES($id,$method,$path,$status,$remote,$now);";q.Parameters.AddWithValue("$id",(object?)id??DBNull.Value);q.Parameters.AddWithValue("$method",method);q.Parameters.AddWithValue("$path",path);q.Parameters.AddWithValue("$status",id is null?401:200);q.Parameters.AddWithValue("$remote",(object?)remote??DBNull.Value);q.Parameters.AddWithValue("$now",FormatTimestamp(_timeProvider.GetUtcNow()));await q.ExecuteNonQueryAsync(ct);}return id; }
    public async Task<IReadOnlyList<ApiAuditRecord>> ListApiAuditAsync(int limit,CancellationToken ct=default){await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT id,token_id,method,path,status_code,remote_address,occurred_at_utc FROM api_audit ORDER BY occurred_at_utc DESC LIMIT $limit;";q.Parameters.AddWithValue("$limit",limit);await using var r=await q.ExecuteReaderAsync(ct);var result=new List<ApiAuditRecord>();while(await r.ReadAsync(ct))result.Add(new(r.GetInt64(0),r.IsDBNull(1)?null:r.GetInt64(1),r.GetString(2),r.GetString(3),r.GetInt32(4),r.IsDBNull(5)?null:r.GetString(5),ParseTimestamp(r.GetString(6))));return result;}
}
