using System.Globalization;
using System.Text.Json;
using Microsoft.Data.Sqlite;

namespace CoreWatch.Atlas.Server;

public sealed partial class AtlasDatabase
{
    public async Task<IReadOnlyList<AlertRule>> ListAlertRulesAsync(CancellationToken ct=default)
    {
        await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();
        q.CommandText="SELECT id,name,metric_type,threshold,severity,enabled,duration_seconds,renotify_minutes,escalate_minutes,assignee,target_agent_id,target_group_id FROM alert_rules ORDER BY id;";
        await using var r=await q.ExecuteReaderAsync(ct);var rules=new List<AlertRule>();
        while(await r.ReadAsync(ct))rules.Add(new(r.GetInt64(0),r.GetString(1),r.GetString(2),r.GetDouble(3),r.GetString(4),r.GetInt64(5)==1,r.GetInt32(6),r.GetInt32(7),r.GetInt32(8),AlertText(r,9),r.IsDBNull(10)?null:Guid.Parse(r.GetString(10)),r.IsDBNull(11)?null:r.GetInt64(11)));return rules;
    }
    public async Task<AlertRule> CreateAlertRuleAsync(AlertRuleRequest x,CancellationToken ct=default)
    { ValidateRule(x);await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="INSERT INTO alert_rules(name,metric_type,threshold,severity,enabled,duration_seconds,renotify_minutes,escalate_minutes,assignee,target_agent_id,target_group_id) VALUES($name,$metric,$threshold,$severity,$enabled,$duration,$renotify,$escalate,$assignee,$agent,$group);SELECT last_insert_rowid();";AddRuleParameters(q,x);var id=Convert.ToInt64(await q.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture);return new(id,x.Name.Trim(),x.MetricType,x.Threshold,x.Severity,x.Enabled,x.DurationSeconds,x.RenotifyMinutes,x.EscalateMinutes,x.Assignee,x.TargetAgentId,x.TargetGroupId); }
    public async Task<bool> UpdateAlertRuleAsync(long id,AlertRuleRequest x,CancellationToken ct=default)
    { ValidateRule(x);await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="UPDATE alert_rules SET name=$name,metric_type=$metric,threshold=$threshold,severity=$severity,enabled=$enabled,duration_seconds=$duration,renotify_minutes=$renotify,escalate_minutes=$escalate,assignee=$assignee,target_agent_id=$agent,target_group_id=$group WHERE id=$id;";AddRuleParameters(q,x);q.Parameters.AddWithValue("$id",id);return await q.ExecuteNonQueryAsync(ct)==1; }
    public async Task<bool> DeleteAlertRuleAsync(long id,CancellationToken ct=default){await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="DELETE FROM alert_rules WHERE id=$id;";q.Parameters.AddWithValue("$id",id);return await q.ExecuteNonQueryAsync(ct)==1;}
    public async Task<IReadOnlyList<AlertRecord>> ListAlertsAsync(bool activeOnly,int limit,CancellationToken ct=default)
    { await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT a.id,a.agent_id,g.host_name,a.rule_id,r.name,r.metric_type,a.severity,a.current_value,a.state,a.opened_at_utc,a.resolved_at_utc,a.acknowledged_at_utc,a.acknowledged_by,a.assigned_to FROM alerts a JOIN agents g ON g.agent_id=a.agent_id JOIN alert_rules r ON r.id=a.rule_id WHERE ($active=0 OR a.state='active') ORDER BY a.opened_at_utc DESC LIMIT $limit;";q.Parameters.AddWithValue("$active",activeOnly?1:0);q.Parameters.AddWithValue("$limit",limit);await using var r=await q.ExecuteReaderAsync(ct);var result=new List<AlertRecord>();while(await r.ReadAsync(ct))result.Add(ReadAlert(r));return result; }
    public async Task<bool> AcknowledgeAlertAsync(long id,string username,CancellationToken ct=default)
    { await using var c=await OpenConnectionAsync(ct);await using var tx=(SqliteTransaction)await c.BeginTransactionAsync(ct);await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="UPDATE alerts SET acknowledged_at_utc=$now,acknowledged_by=$user WHERE id=$id AND state='active' AND acknowledged_at_utc IS NULL;";q.Parameters.AddWithValue("$now",FormatTimestamp(_timeProvider.GetUtcNow()));q.Parameters.AddWithValue("$user",username);q.Parameters.AddWithValue("$id",id);var ok=await q.ExecuteNonQueryAsync(ct)==1;if(ok)await AddActionAsync(c,tx,id,"acknowledged",username,null,null,ct);await tx.CommitAsync(ct);return ok; }
    public async Task<IReadOnlyList<AlertAction>> ListAlertActionsAsync(long alertId,CancellationToken ct=default)
    { await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT id,alert_id,action_type,actor,note,assignee,created_at_utc FROM alert_actions WHERE alert_id=$id ORDER BY created_at_utc;";q.Parameters.AddWithValue("$id",alertId);await using var r=await q.ExecuteReaderAsync(ct);var result=new List<AlertAction>();while(await r.ReadAsync(ct))result.Add(new(r.GetInt64(0),r.GetInt64(1),r.GetString(2),r.GetString(3),AlertText(r,4),AlertText(r,5),ParseTimestamp(r.GetString(6))));return result; }
    public async Task<bool> AddAlertActionAsync(long id,AlertActionRequest x,string username,CancellationToken ct=default)
    { if(x.Note?.Length>2000||x.Assignee?.Length>100)throw new ArgumentException("Invalid alert action.");await using var c=await OpenConnectionAsync(ct);await using var tx=(SqliteTransaction)await c.BeginTransactionAsync(ct);await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText=x.Resolve?"UPDATE alerts SET state='resolved',resolved_at_utc=$now,assigned_to=$assignee WHERE id=$id AND state='active';":"UPDATE alerts SET assigned_to=COALESCE($assignee,assigned_to) WHERE id=$id;";q.Parameters.AddWithValue("$now",FormatTimestamp(_timeProvider.GetUtcNow()));q.Parameters.AddWithValue("$assignee",(object?)x.Assignee?.Trim()??DBNull.Value);q.Parameters.AddWithValue("$id",id);var ok=await q.ExecuteNonQueryAsync(ct)==1;if(ok){await AddActionAsync(c,tx,id,x.Resolve?"resolved":x.Assignee is null?"comment":"assigned",username,x.Note,x.Assignee,ct);if(x.Resolve)await QueueNotificationsAsync(c,tx,id,"resolved",ct);}await tx.CommitAsync(ct);return ok; }

    public async Task EvaluateAlertsAsync(Guid agentId,JsonElement metrics,CancellationToken ct=default)
    { foreach(var rule in (await ListAlertRulesAsync(ct)).Where(x=>x.Enabled&&x.MetricType!=AlertMetricTypes.Offline))if(await RuleAppliesAsync(rule,agentId,ct))await SetAlertStateAsync(agentId,rule,TryMetric(metrics,rule.MetricType),ct); }
    public async Task EvaluateOfflineAlertsAsync(TimeSpan offlineAfter,CancellationToken ct=default)
    { var rules=(await ListAlertRulesAsync(ct)).Where(x=>x.Enabled&&x.MetricType==AlertMetricTypes.Offline).ToArray();if(rules.Length==0)return;await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT agent_id,last_seen_at_utc FROM agents WHERE archived_at_utc IS NULL;";await using var r=await q.ExecuteReaderAsync(ct);var agents=new List<(Guid Id,DateTimeOffset? Seen)>();while(await r.ReadAsync(ct))agents.Add((Guid.Parse(r.GetString(0)),r.IsDBNull(1)?null:ParseTimestamp(r.GetString(1))));var now=_timeProvider.GetUtcNow();foreach(var agent in agents)foreach(var rule in rules)if(await RuleAppliesAsync(rule,agent.Id,ct))await SetAlertStateAsync(agent.Id,rule,agent.Seen is null?double.PositiveInfinity:(now-agent.Seen.Value).TotalSeconds,ct); }

    private async Task<bool> RuleAppliesAsync(AlertRule rule,Guid agentId,CancellationToken ct)
    { if(rule.TargetAgentId is not null)return rule.TargetAgentId==agentId;if(rule.TargetGroupId is null)return true;await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT COUNT(*) FROM server_group_members WHERE group_id=$group AND agent_id=$agent;";q.Parameters.AddWithValue("$group",rule.TargetGroupId);q.Parameters.AddWithValue("$agent",agentId.ToString("D"));return Convert.ToInt64(await q.ExecuteScalarAsync(ct))==1; }
    private async Task SetAlertStateAsync(Guid agentId,AlertRule rule,double value,CancellationToken ct)
    {
        var violated=value>=rule.Threshold;var now=_timeProvider.GetUtcNow();await using var c=await OpenConnectionAsync(ct);await using var tx=(SqliteTransaction)await c.BeginTransactionAsync(ct);
        await using var find=c.CreateCommand();find.Transaction=tx;find.CommandText="SELECT id,opened_at_utc,last_notified_at_utc FROM alerts WHERE agent_id=$agent AND rule_id=$rule AND state='active';";find.Parameters.AddWithValue("$agent",agentId.ToString("D"));find.Parameters.AddWithValue("$rule",rule.Id);long? activeId=null;DateTimeOffset? opened=null,lastNotified=null;await using(var r=await find.ExecuteReaderAsync(ct)){if(await r.ReadAsync(ct)){activeId=r.GetInt64(0);opened=ParseTimestamp(r.GetString(1));lastNotified=r.IsDBNull(2)?null:ParseTimestamp(r.GetString(2));}}
        if(!violated){await DeleteViolationAsync(c,tx,agentId,rule.Id,ct);if(activeId is not null){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="UPDATE alerts SET state='resolved',resolved_at_utc=$now,current_value=$value WHERE id=$id;";q.Parameters.AddWithValue("$now",FormatTimestamp(now));q.Parameters.AddWithValue("$value",value);q.Parameters.AddWithValue("$id",activeId);await q.ExecuteNonQueryAsync(ct);await AddActionAsync(c,tx,activeId.Value,"auto-resolved","system",null,null,ct);await QueueNotificationsAsync(c,tx,activeId.Value,"resolved",ct);}await tx.CommitAsync(ct);return;}
        if(activeId is null){var started=await GetOrStartViolationAsync(c,tx,agentId,rule.Id,now,ct);if((now-started).TotalSeconds<rule.DurationSeconds){await tx.CommitAsync(ct);return;}await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO alerts(agent_id,rule_id,severity,current_value,state,opened_at_utc,assigned_to,last_notified_at_utc) VALUES($agent,$rule,$severity,$value,'active',$now,$assignee,$now);SELECT last_insert_rowid();";q.Parameters.AddWithValue("$agent",agentId.ToString("D"));q.Parameters.AddWithValue("$rule",rule.Id);q.Parameters.AddWithValue("$severity",rule.Severity);q.Parameters.AddWithValue("$value",value);q.Parameters.AddWithValue("$now",FormatTimestamp(now));q.Parameters.AddWithValue("$assignee",(object?)rule.Assignee??DBNull.Value);var id=Convert.ToInt64(await q.ExecuteScalarAsync(ct));await AddActionAsync(c,tx,id,"opened","system",null,rule.Assignee,ct);await QueueNotificationsAsync(c,tx,id,"opened",ct);}
        else {var severity=rule.EscalateMinutes>0&&(now-opened!.Value).TotalMinutes>=rule.EscalateMinutes?"critical":rule.Severity;await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="UPDATE alerts SET current_value=$value,severity=$severity WHERE id=$id;";q.Parameters.AddWithValue("$value",value);q.Parameters.AddWithValue("$severity",severity);q.Parameters.AddWithValue("$id",activeId);await q.ExecuteNonQueryAsync(ct);if(rule.RenotifyMinutes>0&&(lastNotified is null||(now-lastNotified.Value).TotalMinutes>=rule.RenotifyMinutes)){await QueueNotificationsAsync(c,tx,activeId.Value,"reminder",ct);await using var mark=c.CreateCommand();mark.Transaction=tx;mark.CommandText="UPDATE alerts SET last_notified_at_utc=$now WHERE id=$id;";mark.Parameters.AddWithValue("$now",FormatTimestamp(now));mark.Parameters.AddWithValue("$id",activeId);await mark.ExecuteNonQueryAsync(ct);}}
        await tx.CommitAsync(ct);
    }
    private static async Task<DateTimeOffset> GetOrStartViolationAsync(SqliteConnection c,SqliteTransaction tx,Guid agent,long rule,DateTimeOffset now,CancellationToken ct){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT OR IGNORE INTO alert_rule_violations(agent_id,rule_id,started_at_utc) VALUES($agent,$rule,$now);SELECT started_at_utc FROM alert_rule_violations WHERE agent_id=$agent AND rule_id=$rule;";q.Parameters.AddWithValue("$agent",agent.ToString("D"));q.Parameters.AddWithValue("$rule",rule);q.Parameters.AddWithValue("$now",FormatTimestamp(now));return ParseTimestamp(Convert.ToString(await q.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture)!);}
    private static async Task DeleteViolationAsync(SqliteConnection c,SqliteTransaction tx,Guid agent,long rule,CancellationToken ct){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="DELETE FROM alert_rule_violations WHERE agent_id=$agent AND rule_id=$rule;";q.Parameters.AddWithValue("$agent",agent.ToString("D"));q.Parameters.AddWithValue("$rule",rule);await q.ExecuteNonQueryAsync(ct);}
    private static async Task AddActionAsync(SqliteConnection c,SqliteTransaction tx,long id,string type,string actor,string? note,string? assignee,CancellationToken ct){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO alert_actions(alert_id,action_type,actor,note,assignee,created_at_utc) VALUES($id,$type,$actor,$note,$assignee,strftime('%Y-%m-%dT%H:%M:%fZ','now'));";q.Parameters.AddWithValue("$id",id);q.Parameters.AddWithValue("$type",type);q.Parameters.AddWithValue("$actor",actor);q.Parameters.AddWithValue("$note",(object?)note??DBNull.Value);q.Parameters.AddWithValue("$assignee",(object?)assignee??DBNull.Value);await q.ExecuteNonQueryAsync(ct);}
    private static double TryMetric(JsonElement m,string type){try{return type switch{"cpu"=>m.GetProperty("cpu").GetProperty("usageRatio").GetDouble()*100,"memory"=>100*(1-m.GetProperty("memory").GetProperty("availableBytes").GetDouble()/m.GetProperty("memory").GetProperty("totalBytes").GetDouble()),"disk"=>Disk(m),_=>0};}catch{return 0;}}
    private static double Disk(JsonElement m){var total=0d;var free=0d;foreach(var x in m.GetProperty("fileSystems").EnumerateArray()){total+=x.GetProperty("totalBytes").GetDouble();free+=x.GetProperty("availableBytes").GetDouble();}return total==0?0:100*(1-free/total);}
    private static AlertRecord ReadAlert(SqliteDataReader r)=>new(r.GetInt64(0),Guid.Parse(r.GetString(1)),r.GetString(2),r.GetInt64(3),r.GetString(4),r.GetString(5),r.GetString(6),r.GetDouble(7),r.GetString(8),ParseTimestamp(r.GetString(9)),r.IsDBNull(10)?null:ParseTimestamp(r.GetString(10)),r.IsDBNull(11)?null:ParseTimestamp(r.GetString(11)),AlertText(r,12),AlertText(r,13));
    private static string? AlertText(SqliteDataReader r,int i)=>r.IsDBNull(i)?null:r.GetString(i);
    private static void ValidateRule(AlertRuleRequest x){if(string.IsNullOrWhiteSpace(x.Name)||x.Name.Length>80||!new[]{"cpu","memory","disk","offline"}.Contains(x.MetricType)||!new[]{"warning","critical"}.Contains(x.Severity)||x.Threshold<=0||(x.MetricType!="offline"&&x.Threshold>100)||x.Threshold>86400||x.DurationSeconds is <0 or >86400||x.RenotifyMinutes is <0 or >43200||x.EscalateMinutes is <0 or >43200||x.Assignee?.Length>100)throw new ArgumentException("Invalid alert rule.");}
    private static void AddRuleParameters(SqliteCommand q,AlertRuleRequest x){q.Parameters.AddWithValue("$name",x.Name.Trim());q.Parameters.AddWithValue("$metric",x.MetricType);q.Parameters.AddWithValue("$threshold",x.Threshold);q.Parameters.AddWithValue("$severity",x.Severity);q.Parameters.AddWithValue("$enabled",x.Enabled?1:0);q.Parameters.AddWithValue("$duration",x.DurationSeconds);q.Parameters.AddWithValue("$renotify",x.RenotifyMinutes);q.Parameters.AddWithValue("$escalate",x.EscalateMinutes);q.Parameters.AddWithValue("$assignee",(object?)x.Assignee??DBNull.Value);q.Parameters.AddWithValue("$agent",(object?)x.TargetAgentId?.ToString("D")??DBNull.Value);q.Parameters.AddWithValue("$group",(object?)x.TargetGroupId??DBNull.Value);}
    private static async Task QueueNotificationsAsync(SqliteConnection c,SqliteTransaction tx,long id,string type,CancellationToken ct){await using var q=c.CreateCommand();q.Transaction=tx;q.CommandText="INSERT INTO notification_deliveries(alert_id,channel_id,event_type,created_at_utc) SELECT $id,id,$type,strftime('%Y-%m-%dT%H:%M:%fZ','now') FROM notification_channels WHERE enabled=1;";q.Parameters.AddWithValue("$id",id);q.Parameters.AddWithValue("$type",type);await q.ExecuteNonQueryAsync(ct);}
}

public sealed partial class AtlasDatabase
{
    public async Task<IReadOnlyList<NotificationChannel>> ListNotificationChannelsAsync(CancellationToken ct=default){await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT id,name,url,enabled,channel_type,template FROM notification_channels ORDER BY id;";await using var r=await q.ExecuteReaderAsync(ct);var result=new List<NotificationChannel>();while(await r.ReadAsync(ct)){var type=r.GetString(4);result.Add(new(r.GetInt64(0),r.GetString(1),RedactChannel(r.GetString(2),type),r.GetInt64(3)==1,type,AlertText(r,5)));}return result;}
    public async Task<NotificationChannel> CreateNotificationChannelAsync(NotificationChannelRequest x,CancellationToken ct=default){ValidateChannel(x);await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="INSERT INTO notification_channels(name,url,enabled,channel_type,template) VALUES($name,$url,$enabled,$type,$template);SELECT last_insert_rowid();";AddChannel(q,x);var id=Convert.ToInt64(await q.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture);return new(id,x.Name.Trim(),RedactChannel(x.Url,x.ChannelType),x.Enabled,x.ChannelType,x.Template);}
    public async Task<bool> UpdateNotificationChannelAsync(long id,NotificationChannelRequest x,CancellationToken ct=default){ValidateChannel(x);await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="UPDATE notification_channels SET name=$name,url=$url,enabled=$enabled,channel_type=$type,template=$template WHERE id=$id;";AddChannel(q,x);q.Parameters.AddWithValue("$id",id);return await q.ExecuteNonQueryAsync(ct)==1;}
    public async Task<bool> DeleteNotificationChannelAsync(long id,CancellationToken ct=default){await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="DELETE FROM notification_channels WHERE id=$id;";q.Parameters.AddWithValue("$id",id);return await q.ExecuteNonQueryAsync(ct)==1;}
    public async Task<IReadOnlyList<(long Id,string Url,string Payload)>> GetPendingNotificationDeliveriesAsync(int limit,CancellationToken ct=default)
    {
        await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();
        q.CommandText="""
            SELECT d.id,ch.url,
              CASE ch.channel_type
                WHEN 'slack' THEN json_object('text',COALESCE(ch.template,'CoreWatch alert')||': '||g.host_name||' / '||r.name||' ('||a.state||')')
                WHEN 'discord' THEN json_object('content',COALESCE(ch.template,'CoreWatch alert')||': '||g.host_name||' / '||r.name||' ('||a.state||')')
                WHEN 'teams' THEN json_object('type','message','text',COALESCE(ch.template,'CoreWatch alert')||': '||g.host_name||' / '||r.name||' ('||a.state||')')
                ELSE json_object('event',d.event_type,'alertId',a.id,'agent',g.host_name,'rule',r.name,'severity',a.severity,'value',a.current_value,'state',a.state,'openedAtUtc',a.opened_at_utc)
              END
            FROM notification_deliveries d
            JOIN notification_channels ch ON ch.id=d.channel_id
            JOIN alerts a ON a.id=d.alert_id JOIN agents g ON g.agent_id=a.agent_id JOIN alert_rules r ON r.id=a.rule_id
            WHERE d.delivered_at_utc IS NULL AND d.attempt_count<5
              AND NOT EXISTS(SELECT 1 FROM maintenance_windows w
                WHERE w.starts_at_utc<=strftime('%Y-%m-%dT%H:%M:%fZ','now') AND w.ends_at_utc>strftime('%Y-%m-%dT%H:%M:%fZ','now')
                  AND (w.agent_id IS NULL AND w.group_id IS NULL OR w.agent_id=a.agent_id OR EXISTS(SELECT 1 FROM server_group_members gm WHERE gm.group_id=w.group_id AND gm.agent_id=a.agent_id)))
            ORDER BY d.id LIMIT $limit;
            """;
        q.Parameters.AddWithValue("$limit",limit);await using var r=await q.ExecuteReaderAsync(ct);var result=new List<(long,string,string)>();while(await r.ReadAsync(ct))result.Add((r.GetInt64(0),r.GetString(1),r.GetString(2)));return result;
    }
    public async Task MarkNotificationDeliveryAsync(long id,bool succeeded,string? error,CancellationToken ct=default){await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="UPDATE notification_deliveries SET attempt_count=attempt_count+1,delivered_at_utc=CASE WHEN $ok=1 THEN $now ELSE NULL END,last_error=$error WHERE id=$id;";q.Parameters.AddWithValue("$id",id);q.Parameters.AddWithValue("$ok",succeeded?1:0);q.Parameters.AddWithValue("$now",FormatTimestamp(_timeProvider.GetUtcNow()));q.Parameters.AddWithValue("$error",error??(object)DBNull.Value);await q.ExecuteNonQueryAsync(ct);}
    private static void ValidateChannel(NotificationChannelRequest x){if(string.IsNullOrWhiteSpace(x.Name)||x.Name.Length>80||!new[]{"generic","slack","teams","discord","email"}.Contains(x.ChannelType)||x.Template?.Length>1000)throw new ArgumentException("Invalid notification channel.");if(x.ChannelType=="email"){try{_ = new System.Net.Mail.MailAddress(x.Url);}catch{throw new ArgumentException("Invalid email address.");}}else if(!Uri.TryCreate(x.Url,UriKind.Absolute,out var uri)||(uri.Scheme!="https"&&uri.Scheme!="http"))throw new ArgumentException("Invalid notification channel URL.");}
    private static void AddChannel(SqliteCommand q,NotificationChannelRequest x){q.Parameters.AddWithValue("$name",x.Name.Trim());q.Parameters.AddWithValue("$url",x.Url.Trim());q.Parameters.AddWithValue("$enabled",x.Enabled?1:0);q.Parameters.AddWithValue("$type",x.ChannelType);q.Parameters.AddWithValue("$template",(object?)x.Template??DBNull.Value);}
    private static string RedactChannel(string value,string type){if(type=="email")return value;return Uri.TryCreate(value,UriKind.Absolute,out var uri)?$"{uri.Scheme}://{uri.Host}/***":"***";}
}
