namespace CoreWatch.Atlas.Server;

public sealed record AgentCommandRecord(long Id,Guid AgentId,string CommandType,string Target,string State,string? Detail,string RequestedBy,DateTimeOffset RequestedAtUtc,DateTimeOffset UpdatedAtUtc);
public sealed record AgentCommandRequest(string CommandType,string Target);
public sealed record AgentCommandStatusRequest(string State,string? Detail);

public sealed partial class AtlasDatabase
{
    public async Task<AgentCommandRecord> RequestAgentCommandAsync(Guid agentId,AgentCommandRequest x,string user,CancellationToken ct=default)
    { if(x.CommandType!="restart-service"||string.IsNullOrWhiteSpace(x.Target)||x.Target.Length>128)throw new ArgumentException("Invalid agent command.");var now=_timeProvider.GetUtcNow();await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="INSERT INTO agent_commands(agent_id,command_type,target,state,requested_by,requested_at_utc,updated_at_utc) VALUES($agent,$type,$target,'pending',$user,$now,$now);SELECT last_insert_rowid();";q.Parameters.AddWithValue("$agent",agentId.ToString("D"));q.Parameters.AddWithValue("$type",x.CommandType);q.Parameters.AddWithValue("$target",x.Target.Trim());q.Parameters.AddWithValue("$user",user);q.Parameters.AddWithValue("$now",FormatTimestamp(now));var id=Convert.ToInt64(await q.ExecuteScalarAsync(ct));return new(id,agentId,x.CommandType,x.Target.Trim(),"pending",null,user,now,now); }
    public async Task<AgentCommandRecord?> GetPendingAgentCommandAsync(Guid agentId,CancellationToken ct=default)
    { await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT id,command_type,target,state,detail,requested_by,requested_at_utc,updated_at_utc FROM agent_commands WHERE agent_id=$agent AND state='pending' ORDER BY id LIMIT 1;";q.Parameters.AddWithValue("$agent",agentId.ToString("D"));await using var r=await q.ExecuteReaderAsync(ct);return !await r.ReadAsync(ct)?null:new(r.GetInt64(0),agentId,r.GetString(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.GetString(5),ParseTimestamp(r.GetString(6)),ParseTimestamp(r.GetString(7))); }
    public async Task<bool> UpdateAgentCommandAsync(Guid agentId,long id,AgentCommandStatusRequest x,CancellationToken ct=default)
    { if(!new[]{"running","succeeded","failed","rejected"}.Contains(x.State)||x.Detail?.Length>240)throw new ArgumentException("Invalid command status.");await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="UPDATE agent_commands SET state=$state,detail=$detail,updated_at_utc=$now WHERE id=$id AND agent_id=$agent AND state IN ('pending','running');";q.Parameters.AddWithValue("$state",x.State);q.Parameters.AddWithValue("$detail",(object?)x.Detail??DBNull.Value);q.Parameters.AddWithValue("$now",FormatTimestamp(_timeProvider.GetUtcNow()));q.Parameters.AddWithValue("$id",id);q.Parameters.AddWithValue("$agent",agentId.ToString("D"));return await q.ExecuteNonQueryAsync(ct)==1; }
    public async Task<IReadOnlyList<AgentCommandRecord>> ListAgentCommandsAsync(Guid agentId,CancellationToken ct=default)
    { await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT id,command_type,target,state,detail,requested_by,requested_at_utc,updated_at_utc FROM agent_commands WHERE agent_id=$agent ORDER BY id DESC LIMIT 100;";q.Parameters.AddWithValue("$agent",agentId.ToString("D"));await using var r=await q.ExecuteReaderAsync(ct);var result=new List<AgentCommandRecord>();while(await r.ReadAsync(ct))result.Add(new(r.GetInt64(0),agentId,r.GetString(1),r.GetString(2),r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),r.GetString(5),ParseTimestamp(r.GetString(6)),ParseTimestamp(r.GetString(7))));return result; }
}
