namespace CoreWatch.Atlas.Server;

public sealed partial class AtlasDatabase
{
    public async Task<IReadOnlyList<MaintenanceWindow>> ListMaintenanceWindowsAsync(CancellationToken ct=default)
    { await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT id,name,starts_at_utc,ends_at_utc,agent_id,group_id FROM maintenance_windows WHERE ends_at_utc>=strftime('%Y-%m-%dT%H:%M:%fZ','now') ORDER BY starts_at_utc;";await using var r=await q.ExecuteReaderAsync(ct);var x=new List<MaintenanceWindow>();while(await r.ReadAsync(ct))x.Add(new(r.GetInt64(0),r.GetString(1),ParseTimestamp(r.GetString(2)),ParseTimestamp(r.GetString(3)),r.IsDBNull(4)?null:Guid.Parse(r.GetString(4)),r.IsDBNull(5)?null:r.GetInt64(5)));return x; }
    public async Task<MaintenanceWindow> CreateMaintenanceWindowAsync(MaintenanceWindowRequest x,CancellationToken ct=default)
    { if(string.IsNullOrWhiteSpace(x.Name)||x.Name.Length>80||x.EndsAtUtc<=x.StartsAtUtc||x.EndsAtUtc-x.StartsAtUtc>TimeSpan.FromDays(30)||x.AgentId is not null&&x.GroupId is not null)throw new ArgumentException("Invalid maintenance window.");await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="INSERT INTO maintenance_windows(name,starts_at_utc,ends_at_utc,agent_id,group_id) VALUES($n,$s,$e,$agent,$group);SELECT last_insert_rowid();";q.Parameters.AddWithValue("$n",x.Name.Trim());q.Parameters.AddWithValue("$s",FormatTimestamp(x.StartsAtUtc));q.Parameters.AddWithValue("$e",FormatTimestamp(x.EndsAtUtc));q.Parameters.AddWithValue("$agent",(object?)x.AgentId?.ToString("D")??DBNull.Value);q.Parameters.AddWithValue("$group",(object?)x.GroupId??DBNull.Value);var id=Convert.ToInt64(await q.ExecuteScalarAsync(ct));return new(id,x.Name.Trim(),x.StartsAtUtc,x.EndsAtUtc,x.AgentId,x.GroupId); }
    public async Task<bool> DeleteMaintenanceWindowAsync(long id,CancellationToken ct=default){await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="DELETE FROM maintenance_windows WHERE id=$id;";q.Parameters.AddWithValue("$id",id);return await q.ExecuteNonQueryAsync(ct)==1;}
    public async Task<bool> IsMaintenanceActiveAsync(CancellationToken ct=default)
    { await using var c=await OpenConnectionAsync(ct);await using var q=c.CreateCommand();q.CommandText="SELECT EXISTS(SELECT 1 FROM maintenance_windows WHERE starts_at_utc<=strftime('%Y-%m-%dT%H:%M:%fZ','now') AND ends_at_utc>strftime('%Y-%m-%dT%H:%M:%fZ','now'));";return Convert.ToInt64(await q.ExecuteScalarAsync(ct))==1; }
}
